instance_groups:
- azs:
  - Sandbox-PKS-Management
  instances: 1
  jobs:
  - name: telegraf
    release: monitoring-agents
    properties:
      influxdb_agent_interval: "10s"
      influxdb_output_retention_policy: "default"
      influxdb_telegraf:
      - url: "http://appdynamics.preprod.cloud.local.dub:8086"
        db: "PKS-Sandbox_telegraf"
        username: "grafana"
        password: "grafana"
        user_agent: "telegraf"
  - name: appdynamics-machineagent
    release: monitoring-agents
    properties:
      appdynamics_controller_host_name: sh-preprod-appdynamics.dub
      appdynamics_controller_port: 80
      appdynamics_controller_ssl_enabled: false
      appdynamics_agent_account_name: "customer1"
      appdynamics_agent_account_access_key: "17dc4fa4-11ee-4331-988c-1f26a7b3c71b"
      appdynamics_agent_application_name: "Slotomania Preprod"
      appdynamics_docker_enabled: false
      appdynamics_sim_enabled: false
  name: monitoring-agents
  networks:
  - name: PKS-Sandbox-Management-Network
  stemcell: default
  vm_type: nano
name: monitoring-agents-test
releases:
- name: monitoring-agents
  version: latest
stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest
update:
  canaries: 1
  canary_watch_time: 15000-30000
  max_in_flight: 3
  update_watch_time: 15000-300000

