releases:
- {name: monitoring-agents, version: 0+dev.14}

addons:
- name: monitoring-agents
  jobs:
  - name: telegraf
    release: monitoring-agents
    properties:
      influxdb_agent_interval: "10s"
      influxdb_telegraf:
      - url: "http://192.168.178.118:8086"
        db: "server1-db"
  include:
    deployments: [service-instance_a034c619-3395-44b7-9f92-2eb7928328bd]
